### ISSUE TITLE
TL-B support

### ISSUE THREAD

**Issue by AndreyKostromskoy** [unserialize/TL-Schema-idea-plugin#4]
Please support .tlb files https://github.com/ton-blockchain/ton/blob/master/crypto/tl/hashmap.tlb
https://github.com/ton-blockchain/ton/blob/master/crypto/tl/boc.tlb

**Comment by andreypfau** [comment]
@AndreyKostromskoy You can use this for TL-B support:
https://github.com/andreypfau/intellij-ton/

**Comment by Danil42Russia** [comment]
This is not in the plans. You can use the solution from @andreypfau
